CONTRIBUTING.MD
README.md
client/head.html
imports/api/example/exampleCollection.js
imports/api/example/methods.js
imports/startup/server/index.js
imports/ui/layouts/body/body.html
imports/ui/stylesheets/_newExampleForm.scss
imports/ui/stylesheets/bundle.scss
package-lock.json

Solution: Added some paddings and margin to center the form and added a title up top.

Problem: The UI is ugly and needs to fixed #5

---

.travis.yml
wdio.conf.js

Solution: Implement Travis CI server and client side tests.

Problem: No test framework has been implemented (#13)

---

.meteor/packages
.meteor/versions
imports/modules/notifier.js
imports/startup/client/index.js
imports/startup/client/routes.js
imports/ui/layouts/auth/auth.html
imports/ui/layouts/auth/auth.js
imports/ui/pages/login/login.html
imports/ui/pages/login/login.js
imports/ui/pages/signup/signup.html
imports/ui/pages/signup/signup.js
imports/ui/shared/header/header.html
imports/ui/shared/header/header.js
imports/ui/stylesheets/_custom.scss
imports/ui/stylesheets/bundle.scss
imports/ui/stylesheets/theme/noty.scss
package-lock.json
package.json

solution: installed and implement user-accounts. Created login and signup pages. installed noty for notifications and error messages

problem: no auth system #17

---

.gitignore
imports/api/user/methods.js
imports/startup/server/register-api.js
imports/ui/pages/login/login.ui-test.js
imports/ui/pages/signup/signup.ui-test.js
imports/ui/shared/header/header.ui-test.js
package-lock.json
package.json

Solution: added client side tests for auth pages i.e sign in and sign up. added client side tests for the header

Problem: auth isn't tested #20

---

imports/ui/pages/login/login.ui-test.js
imports/ui/pages/signup/signup.ui-test.js
imports/ui/shared/header/header.ui-test.js
package-lock.json
package.json

Solution: Fix failing tests by adding appropriate pauses everywhere.

Problem: Auth tests are failing in the CI (#21)

---

imports/api/userQuestions/methods.js
imports/api/userQuestions/methods.test.js
imports/api/userQuestions/userQuestions.js
imports/api/utilities.js
imports/modules/autoform-typeahead/autoform-typeahead.css
imports/modules/autoform-typeahead/autoform-typeahead.html
imports/modules/autoform-typeahead/autoform-typeahead.js
imports/startup/client/index.js
imports/startup/client/routes.js
imports/startup/server/register-api.js
imports/ui/pages/userInfo/userInfo.html
imports/ui/pages/userInfo/userInfo.js
imports/ui/shared/sidebar/sidebar.html
package-lock.json
package.json

Solution: Add a new form for personal user questions at `/userInfo` route. Implement a typeahead component for autoform that can be used easily from now on. Write appropriate tests.

Problem: User question form not added to emurpas (#24)

---

imports/api/project-questions/methods.js
imports/api/project-questions/methods.test.js

Solution: Write server side Mocha tests to ensure everything is working properly.

Problem: ProjectQuestions is untested (#26)

---

client/head.html
imports/ui/pages/login/login.html
imports/ui/pages/signup/signup.html

solution: add reactive elements and clean up UX #37

problem: login UX is bad

---

imports/api/form-progress/methods.js
imports/api/project-questions/methods.js
imports/api/userQuestions/methods.js
imports/api/userQuestions/methods.test.js
imports/api/userQuestions/userQuestions.js
imports/startup/client/routes.js
imports/ui/pages/userInfo/userInfo.html
imports/ui/pages/userInfo/userInfo.js

solution: used meteor to break down the userQuestions form. updated tests

problem: user-info form too large #36

---

imports/api/form-progress/methods.test.js

solution: added tests updateFormProgress function

problem: no server side tests for FormProgress methods #43

---

imports/api/project-questions/methods.js
imports/api/user/methods.js
imports/api/userQuestions/methods.js
imports/ui/pages/applications/new.ui-test.js
imports/ui/pages/userInfo/userInfo.ui-test.js

Solution: Write client side tests for wizard forms (new application form and user info form).

Problem: No client side tests added for wizard forms (#44)

---

imports/api/project-questions/project-questions.js
imports/ui/pages/home/home.html
imports/ui/pages/home/home.js

solution: add ability to resume in-progress application #34

problem: user cannot view in-progress forms

---

imports/api/form-progress/form-progress.js
imports/ui/pages/applications/new.js
imports/ui/pages/home/home.js

solution: redirect to existing application if one is in progress #35

problem: user able to start a new application while another exists

---

imports/api/form-progress/form-progress.js
imports/ui/pages/applications/new.js

Solution: Fix broken client-side tests.

Problem: Tests are broken (#50)

---

imports/api/form-progress/form-progress.js
imports/api/form-progress/methods.test.js
imports/api/project-questions/methods.js
imports/api/project-questions/methods.test.js
imports/api/project-questions/project-questions.js
imports/api/user/methods.js
imports/api/user/methods.test.js
imports/api/user/server/publications.js
imports/api/userQuestions/methods.test.js
imports/startup/client/routes.js
imports/startup/server/register-api.js
imports/ui/helpers/handlebars-helpers.js
imports/ui/pages/applications/new.ui-test.js
imports/ui/pages/moderator/application/modApplication.html
imports/ui/pages/moderator/application/modApplication.js
imports/ui/pages/moderator/applications/modApplications.html
imports/ui/pages/moderator/applications/modApplications.js
imports/ui/pages/moderator/users/modUsers.html
imports/ui/pages/moderator/users/modUsers.js
imports/ui/pages/moderator/users/modUsers.ui-test.js
imports/ui/shared/sidebar/sidebar.html
package-lock.json
package.json

Solution: Implement a simple moderator section where moderators can view/remove applications and promote/demote users. Add appropriate client side and server side tests.

Problem: No moderator section to view applications (#55)

---

imports/api/user/server/accounts.js
imports/startup/server/register-api.js
imports/ui/helpers/handlebars-helpers.js
imports/ui/pages/home/home.html
imports/ui/shared/sidebar/sidebar.html

Solution: Additional team members are directed straight to the personal question area when they register and they are not given an opportunity to start a new application.

Problem: Additional team members are treated like new users (#54)

---

imports/api/project-questions/methods.test.js
imports/api/project-questions/project-questions.js
imports/ui/pages/applications/new.ui-test.js

Solution: Fix the validation in the project questions schema.

Problem: Invalid validation (#53)

---

imports/api/form-progress/form-progress.js
imports/startup/client/routes.js
imports/ui/helpers/handlebars-helpers.js
imports/ui/pages/applications/viewApplication.html
imports/ui/pages/applications/viewApplication.js
imports/ui/pages/home/home.html
imports/ui/pages/home/home.js

Solution: created a viewApplication. users redirected to view application if application is complete

Problem: clicking on saved applications in home is unresponsive #49

---

imports/ui/pages/home/home.html
imports/ui/pages/home/home.js

solution: used moment to format timestamps. added an author column

problem: timestamps not properly formatted #61

---

imports/api/example/exampleCollection.js
imports/api/example/methods.js
package-lock.json

Solution: User should only be able to submit if the terms are agreed

problem: User able to submit form when terms not agreed #63

---

AUTHORS
package-lock.json
package.json

solution: updated packages with vulnerabilities. added name to AUTHORS file

problem: outdated bootstrap version used, has vulnerabilities #69

---

imports/ui/stylesheets/bootstrap/_bootstrap.scss

solution: attempted fix - added missing bootstrap variables file

problem: master is broken #71

---

imports/ui/pages/moderator/application/modApplication.js
imports/ui/pages/moderator/applications/modApplications.html
imports/ui/pages/moderator/applications/modApplications.js

solution: mod can view form progress details. clicking on view redirects to the single application page

problem: moderators cannot view applications #73

---

imports/api/question-rating/methods.js
imports/api/question-rating/question-rating.js
imports/api/question-rating/server/publications.js
imports/startup/server/register-api.js
imports/ui/pages/applications/viewApplication.html
imports/ui/pages/applications/viewApplication.js
imports/ui/pages/moderator/application/modApplication.html
imports/ui/pages/moderator/application/modApplication.js

solution: mods able to rate responses. added question rating collection and associated methods. UI modifications to viewApplication and mod viewApplication pages

problem: maintainers cannot rate responses #80

---

imports/ui/pages/home/home.html

solution: add introduction text

problem: no introduction text

---

.gitignore
AUTHORS
imports/ui/pages/applications/new.js

Solution : Form values for populating questions updated

Problem: self-populating questions not working #83

---

imports/ui/pages/home/home.html

solution: improve welcome text

problem: welcome text not friendly

---

imports/ui/pages/home/home.html

problem: p tag not closed

---

imports/ui/pages/applications/new.js

Solution: redirect the user to home route on form completion

problem:users can access personal form after submitting it #89

---

imports/api/form-progress/form-progress.js
imports/api/project-questions/project-questions.js
imports/api/user/server/publications.js
imports/ui/pages/home/home.html
imports/ui/pages/home/home.js

Solution: Let all users associated with the application view (not edit) the application.

Problem: Not all users associated with an application can view it (#90)

---

imports/api/userQuestions/userQuestions.js
imports/ui/helpers/handlebars-helpers.js
imports/ui/shared/sidebar/sidebar.html

Solution: Don't show the incorrect text if user has submitted their personal info form.

Problem: Users shown incorrect text on form completion (#88)

---

.meteor/packages
imports/api/comments/comments.js
imports/api/comments/methods.js
imports/api/comments/methods.test.js
imports/api/comments/server/publications.js
imports/startup/client/index.js
imports/startup/server/register-api.js
imports/ui/helpers/handlebars-helpers.js
imports/ui/pages/applications/new.js
imports/ui/pages/applications/new.ui-test.js
imports/ui/pages/applications/viewApplication.html
imports/ui/pages/applications/viewApplication.js
imports/ui/pages/comments/commentBody.html
imports/ui/pages/comments/commentBody.js
imports/ui/pages/moderator/application/modApplication.html
imports/ui/pages/moderator/application/modApplication.js
imports/ui/stylesheets/_custom.scss
package-lock.json
package.json

Solution: Implement a simple hierarchical commenting system that allows users associated with the application to comment/add more data on each answer in the application and that allows moderators to ask additional questions about each answer. The commenting system enables easy communication between moderators and users that are applying. Add appropriate client-side tests and server-side tests for the commenting system.

Problem: Users and moderators can't comment on answers or ask questions (#96, #97)

---

imports/ui/helpers/handlebars-helpers.js
imports/ui/pages/home/home.html

solution: Adds background color & icon to the questions created by mods

problem: questions from mods not distinguished from answers

---

imports/ui/pages/comments/commentBody.js
imports/ui/pages/home/home.js
imports/ui/pages/signup/signup.html
imports/ui/pages/signup/signup.js

solution: Adds username field to the signup form

problem: user emails are used instead of user names #102

---

imports/api/question-rating/methods.js
imports/ui/pages/moderator/application/modApplication.html
imports/ui/pages/moderator/application/modApplication.js

solution: Adds functionality to edit a rating of a question for moderators

problem: moderators cannot change rating of questions #105

---

imports/api/comments/methods.js
imports/api/comments/server/publications.js
imports/ui/pages/comments/commentBody.html
imports/ui/pages/comments/commentBody.js
imports/ui/pages/moderator/application/modApplication.html
imports/ui/pages/moderator/application/modApplication.js

Solution:
Added an extra flag to comments
Filtered publication of comments based on the flag
Updated UI to enable posting moderator only comments/to display if a comment is for moderators only

problem: moderators cannot comment internally #106

---

imports/ui/pages/applications/viewApplication.js
imports/ui/pages/moderator/application/modApplication.js

Solution: Closing forms on success

Problem comment form doesn't close on success #111

---

imports/ui/pages/home/home.html
imports/ui/pages/home/home.js
package-lock.json

Solution : Added user check before projectQuestions subscription

Problem: logged out users can see private info #95

---

client/head.html
client/main.js
imports/api/delegates/delegates.js
imports/api/delegates/methods.js
imports/api/delegates/methods.test.js
imports/api/delegates/server/publications.js
imports/api/project-questions/project-questions.js
imports/api/question-rating/methods.js
imports/startup/server/register-api.js
imports/ui/pages/home/home.js
imports/ui/pages/moderator/application/modApplication.html
imports/ui/pages/moderator/application/modApplication.js
imports/ui/pages/signup/signup.ui-test.js
package-lock.json
package.json

Solution: Allow moderators to delegate their rating votes to other moderators. Allow them to choose whether to delegate the vote on the current application only or on all applications. Allow them to revoke delegations.

Problem: Moderators cannot delegate their vote to another moderator (#107)

---

imports/ui/pages/userInfo/userInfo.js

Solution: Fix the helper that was causing the issue.

Problem: Each step of user info form is stored separately (#118)

---

imports/api/user/methods.js
imports/ui/pages/applications/new.ui-test.js

Solution: Add client-side tests for the delegation system and for the voting system.

Problem: No client-side tests for the delegation system (#116)

---

imports/ui/shared/header/header.html
imports/ui/shared/header/header.js
imports/ui/shared/header/header.scss

Solution : Navigation layout updated for small screens and sidebar toggler button fixed

Problem : Navigation broken on small screen #120

---

imports/ui/shared/header/header.js

Solution : Added check for opened sidebar on starting before toggle sidebar-open

Problem: hamburger menu doesn't work #138

---

imports/ui/shared/header/header.html

Solution : Link updated for dashboard

Problem: “Dashboard” on top doesn’t work #134

---

imports/ui/shared/header/header.html
imports/ui/shared/header/header.scss

Solution : Username added on top navigation and sign out option moved into dropdown option

Problem: users can’t view their name #137

---

imports/ui/pages/home/home.js
imports/ui/shared/header/header.html
imports/ui/shared/sidebar/sidebar.html

Solution : New application and user questions removed for moderators and home page redirected to /moderator/applications

Problem: Mods can submit new application & personal data #129

---

imports/ui/pages/home/home.js

Problem : Cannot read property 'moderator'
Solution : extra check added for user and moderator after PR 145

Problem : home page broken for moderator after PR 145

---

imports/ui/pages/moderator/applications/modApplications.html
imports/ui/pages/moderator/applications/modApplications.js
wdio.conf.js

Solution: Allow moderators to search through applications by creator's name, creator's email address, names and email addresses of team members on the application, problem description and application status.

Problem: Moderators cannot search through applications (#133)

---

imports/ui/pages/moderator/application/modApplication.html
imports/ui/pages/moderator/applications/modApplications.html
package-lock.json

solution: remove the remove button #123

problem: moderators can accidentally delete applications

---

imports/startup/client/routes.js

Solution: Fixed onLogout redirect

problem: 404 when moderator signs out #151

---

imports/api/comments/server/publications.js
imports/api/delegates/server/publications.js
imports/api/form-progress/form-progress.js
imports/api/project-questions/project-questions.js

Solution: Returning early from publications that require a logged in user if we have no Meteor.userId()

Problem: Errors in publications during logout #157

---

imports/ui/pages/signup/signup.html

Solution: Bootstrap class increase as accurate size.

Problem: Registration page look clumsy #160

---

AUTHORS
imports/ui/pages/signup/signup.js

Solution: Add validation with RegExp.

Problem: Registration email validation not exist #161

---

imports/modules/autoform-typeahead/autoform-typeahead.js
imports/ui/pages/userInfo/userInfo.html
imports/ui/pages/userInfo/userInfo.js

Solution: Fixed data loading and when we show the wizard

Problem: user questions not loaded resume #164

---

.meteor/packages
.meteor/versions
imports/api/comments/methods.js
imports/api/elo/elo.js
imports/api/elo/eloRankings.js
imports/api/elo/methods.js
imports/api/elo/server/publications.js
imports/api/elo/server/startup.js
imports/api/project-questions/methods.js
imports/api/project-questions/project-questions.js
imports/api/question-rating/methods.js
imports/startup/server/index.js
imports/startup/server/register-api.js
imports/startup/server/startup.js
imports/ui/pages/applications/new.ui-test.js
imports/ui/pages/applications/viewApplication.js
imports/ui/pages/moderator/application/modApplication.html
imports/ui/pages/moderator/application/modApplication.js
imports/ui/pages/moderator/applications/modApplications.html
imports/ui/pages/moderator/applications/modApplications.js

Solution: Replace the nominal rating system with an ELO ranking system. Recycle most of the ELO ranking code from Blockrazor. Implement the given layout and allow moderators to rank question answers from two applications side by side. Modify the delegate system and the commenting system so they work with the new layout. Show the ELO ranking on applications page and show it for each question. Fix the commenting system problems shown in #159.

Problem: Nominal ratings are difficult to compare (#153, #159)

---

imports/api/form-progress/methods.js
imports/ui/pages/applications/new.js
imports/ui/pages/applications/new.scss
imports/ui/pages/userInfo/userInfo.js
imports/ui/pages/userInfo/userInfo.scss

Solution: Saving form data per field on blur in UserInfo forms

problem: applicant can’t save their progress #135

---

imports/api/form-progress/methods.js
imports/api/userQuestions/methods.js
imports/ui/pages/applications/new.ui-test.js

Problem: new application tests are failing #169

---

imports/api/form-progress/methods.js
imports/api/project-questions/application-count.js
imports/api/project-questions/methods.js
imports/api/project-questions/project-questions.js
imports/ui/pages/home/home.html
imports/ui/pages/moderator/applications/modApplications.html

Solution : Instead of random string, new id field with auto increasing index added

Problem: application ID is hard to follow up #144

---

imports/api/elo/methods.js
imports/api/elo/methods.test.js
imports/api/form-progress/methods.test.js
imports/api/project-questions/methods.js
imports/api/project-questions/project-questions.js
imports/api/userQuestions/methods.js
imports/ui/pages/applications/new.ui-test.js
imports/ui/pages/moderator/application/modApplication.js

Solution: Add client-side and server-side tests. Fix small regressions. Fix other failing server-side tests.

Problem: No tests for the ELO system (#167)

---

imports/api/user/methods.js
imports/startup/client/routes.js
imports/ui/pages/userProfile/editProfile.html
imports/ui/pages/userProfile/userProfile.js
imports/ui/pages/userProfile/userProfile.scss
imports/ui/pages/userProfile/viewProfile.html
imports/ui/shared/header/header.html
imports/ui/shared/header/header.js

Solution: View Profile and Edit Profile added

Problem: Profile setting not available #173

---

imports/ui/pages/userProfile/viewProfile.html

Solution: Wrap card-body with card class of div

Problem: [View Profile] Table look odd #175

---

imports/api/form-progress/methods.js
imports/api/project-questions/methods.js
imports/api/project-questions/project-questions.js
imports/ui/pages/applications/new.js
imports/ui/pages/moderator/application/modApplication.js
imports/ui/pages/moderator/applications/modApplications.html
imports/ui/pages/moderator/applications/modApplications.js

solution: solution: Rank each application by length. Take the rank and divide by the total number of applications to get a normalized rating. Display this in the UI somewhere (probably in the table where all the applications can be seen by moderators). Find some way to display it nicely or log an issue for a UI person to claim. #154

problem: moderators cant quickly see length of application

---

imports/startup/client/routes.js

solution: scroll to the top when you change routes #178

problem: page does not scroll to top

---

imports/api/contact/methods.js
imports/startup/client/routes.js
imports/ui/pages/contact/newContact.html
imports/ui/pages/contact/newContact.js
imports/ui/stylesheets/_custom.scss

Solution: Given access of contact page without login.

problem: users need to login for contact page #186

---

imports/api/elo/methods.js

Solution: update query delete records every 10 minute.

problem: applications disappeared after logged out #184

---

imports/ui/pages/applications/new.js

Solution: scroll to top when click on next or back.

Problem: [new appication] not scroll to top when click on next #194

---

imports/ui/pages/applications/viewApplication.js

Solution : Application ID field added to exclude list

Problem: user can comment on application id #191

---

imports/api/elo/methods.js
imports/ui/pages/moderator/applications/modApplications.html
imports/ui/pages/moderator/applications/modApplications.js

Solution: Implement sorting by application number, date, elo, application weight and application status. Implement filtering by status.

Problem: No filtering for application search bar (#198)

---

imports/ui/pages/userProfile/userProfile.js
imports/ui/shared/header/header.html
imports/ui/shared/header/header.js

solution: hide the profile menu until a bio is set and force the user to complete the profile #202

problem: cannot open profile

---

imports/ui/pages/moderator/applications/modApplications.html
imports/ui/pages/moderator/applications/modApplications.js

solution: added a color indicator #187

problem: weight UI is ugly and complex

---

imports/ui/pages/home/home.js

Solution: Force the user to fill out user information after he has completed an applcation.

Problem: Applicant can skip filling "user information" (#197)

---

imports/api/userQuestions/methods.js

Problem: UserInfo not saved #208

---

imports/api/userQuestions/userQuestions.js
imports/ui/pages/applications/viewApplication.html
imports/ui/pages/applications/viewApplication.js

solution: Adds status for the application on the user application route.
Added status:
- Incomplete application form
- Waiting for team members to complete personal information
- Your application is being reviewed
- The reviewers have questions for you, please view your application to respond
- Rejected

problem: no application status description #132

---

imports/ui/pages/home/home.js

Solution: Postpone redirection until all subscriptions are loaded.

Problem: Redirect to userInfo even if filled  #207

---

imports/ui/pages/applications/viewApplication.html
imports/ui/pages/applications/viewApplication.js

Solution: Showing the incremental id instead of the database related _id

problem: application ID number is different #211

---

imports/api/project-questions/methods.js
imports/api/user/methods.js
imports/ui/pages/applications/new.ui-test.js
imports/ui/shared/header/header.ui-test.js

Solution: Fixed how we generate test applications + Fixed tests

Problem: wdio tests are failing #216

---

imports/ui/pages/applications/new.html
imports/ui/pages/applications/new.js

Solution: 'Next' is now 'Save and Next' and edit will appy only when Save button is click

problem: "save" and "edit" option for filling form is not obvious #136

---

imports/ui/pages/applications/new.html
imports/ui/pages/applications/new.js

problem: forms do not autosave on user input

---

imports/api/contact/methods.js
imports/api/contact/methods.test.js
imports/ui/pages/contact/contact.html
imports/ui/pages/contact/newContact.html
imports/ui/pages/contact/newContact.js
imports/ui/pages/contact/viewContact.html

Solution: Add email field to the contact form and show it on contact info page so moderators can follow up.

Problem: No input of email in "contact" (#223)

---

imports/api/contact/methods.js
imports/ui/pages/contact/newContact.html

Solution: added email validation

Problem: [Contact] email input accept any string, no validation #227

---

imports/startup/client/routes.js

Problem: [Contact] without login, it should not access like other #229

---

imports/ui/pages/login/login.html

Solution: remove scroll with add new class

Problem: [Login] Page having horizontal scroll #230

---

imports/api/elo/methods.js
imports/api/project-questions/methods.js
imports/api/project-questions/methods.test.js
imports/api/project-questions/project-questions.js
imports/ui/pages/home/home.js
imports/ui/pages/moderator/applications/modApplications.js
imports/ui/shared/sidebar/sidebar.html
imports/ui/shared/sidebar/sidebar.js
package.json

Solution: Asks users before creating an application for new or update

problem: users can create multiple applications #225

---

imports/api/user/server/accounts.js

Solution: made onCreateUser more resilient

Problem: registration doesn't work locally #238

---

imports/ui/redirectionModalHelper.js

Solution:
- Extended modal with view Application button
- Added problem_description into the modal text

problem: new users not given context #226

---

imports/api/userQuestions/userQuestions.js

Solution: removed unused duplicate

Problem: duplicate publish #241

---

README.md

solution: Add a reminder in Readme.

problem: Reminder missing

---

.meteor/packages
.meteor/versions
imports/api/comments/server/publications.js
imports/api/elo/server/publications.js
imports/api/form-progress/form-progress.js
imports/api/question-rating/server/publications.js
imports/api/userQuestions/userQuestions.js
imports/ui/pages/applications/viewApplication.js
imports/ui/pages/contact/contact.js
imports/ui/pages/moderator/application/modApplication.js
package.json

Solution: reviewed and tightened publications

Problem: broad publications security issue #243

---

imports/ui/shared/sidebar/sidebar.js
imports/ui/shared/sidebar/sidebar.scss

Solution:
- Formatted the code a bit
- Redirecting to login if the user is not logged in
- Redirecting to a new application if the user marked something as invalid or if the user wants to add a new project

Problem: new application not redirect #247

---

imports/ui/shared/sidebar/sidebar.js

Problem: error in sidebar.js:68: Swal typo #245

---

imports/ui/helpers/htmlEscape.js
imports/ui/shared/sidebar/sidebar.js
imports/ui/shared/sidebar/sidebar.scss

Solution:
- escaping labels before display
- moved to using input: 'radio'

Problem: XSS vulnerability found #250

---

imports/api/project-questions/methods.js
imports/ui/pages/applications/new.js

Solution:
- Disabled editing forms marked as 'completed'
- Added an error notifications to users trying to do that

Problem: users can't update applications #249
